"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 08:17:33.631326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms')),
    sa.UniqueConstraint('name', name=op.f('uq_rooms_name'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('admin', 'motivation_tester', 'technical_tester')", name=op.f('ck_users_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_number', sa.String(length=50), nullable=True),
    sa.Column('group_name', sa.String(length=50), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('scheduled_time', sa.String(length=30), nullable=True),
    sa.Column('passage_order', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('cni', sa.String(length=50), nullable=True),
    sa.Column('physical_file_status', sa.String(length=20), nullable=True),
    sa.Column('piece_number', sa.String(length=50), nullable=True),
    sa.Column('exam_code', sa.String(length=50), nullable=True),
    sa.Column('motivation_completed', sa.Boolean(), nullable=False),
    sa.Column('motivation_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivation_completed_by', sa.Integer(), nullable=True),
    sa.Column('technical_completed', sa.Boolean(), nullable=False),
    sa.Column('technical_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("physical_file_status IS NULL OR physical_file_status IN ('validated', 'missing', 'not_found', 'pending')", name=op.f('ck_candidates_physical_file_status')),
    sa.CheckConstraint('NOT motivation_completed OR exam_code IS NOT NULL', name=op.f('ck_candidates_motivation_has_code')),
    sa.CheckConstraint('NOT technical_completed OR motivation_completed', name=op.f('ck_candidates_technical_after_motivation')),
    sa.ForeignKeyConstraint(['motivation_completed_by'], ['users.id'], name=op.f('fk_candidates_motivation_completed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates')),
    sa.UniqueConstraint('exam_code', name=op.f('uq_candidates_exam_code'))
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_candidate_number'), ['candidate_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_cni'), ['cni'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_group_name'), ['group_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_motivation_completed'), ['motivation_completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_physical_file_status'), ['physical_file_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_scheduled_date'), ['scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_technical_completed'), ['technical_completed'], unique=False)

    op.create_table('workstations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('computer_number', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_workstations_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workstations')),
    sa.UniqueConstraint('room_id', 'computer_number', name='uq_workstation_room_number')
    )
    with op.batch_alter_table('workstations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workstations_room_id'), ['room_id'], unique=False)

    op.create_table('kobo_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kobo_id', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('match_status', sa.String(length=20), nullable=False),
    sa.Column('match_field', sa.String(length=30), nullable=True),
    sa.Column('file_status', sa.String(length=20), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_kobo_submissions_candidate_id_candidates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kobo_submissions')),
    sa.UniqueConstraint('kobo_id', name=op.f('uq_kobo_submissions_kobo_id'))
    )
    with op.batch_alter_table('kobo_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kobo_submissions_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kobo_submissions_match_status'), ['match_status'], unique=False)

    op.create_table('technical_test_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('technical_tester_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('workstation_id', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_pause_seconds', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'paused', 'stopped', 'completed')", name=op.f('ck_technical_test_sessions_status')),
    sa.CheckConstraint('duration_seconds > 0', name=op.f('ck_technical_test_sessions_duration_positive')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_technical_test_sessions_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_technical_test_sessions_room_id_rooms')),
    sa.ForeignKeyConstraint(['technical_tester_id'], ['users.id'], name=op.f('fk_technical_test_sessions_technical_tester_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workstation_id'], ['workstations.id'], name=op.f('fk_technical_test_sessions_workstation_id_workstations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_test_sessions'))
    )
    with op.batch_alter_table('technical_test_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technical_test_sessions_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_technical_test_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_technical_test_sessions_workstation_id'), ['workstation_id'], unique=False)
        batch_op.create_index('uq_active_session_candidate', ['candidate_id'], unique=True, postgresql_where=sa.text("status IN ('running', 'paused')"), sqlite_where=sa.text("status IN ('running', 'paused')"))
        batch_op.create_index('uq_active_session_workstation', ['workstation_id'], unique=True, postgresql_where=sa.text("status IN ('running', 'paused')"), sqlite_where=sa.text("status IN ('running', 'paused')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_test_sessions', schema=None) as batch_op:
        batch_op.drop_index('uq_active_session_workstation', postgresql_where=sa.text("status IN ('running', 'paused')"), sqlite_where=sa.text("status IN ('running', 'paused')"))
        batch_op.drop_index('uq_active_session_candidate', postgresql_where=sa.text("status IN ('running', 'paused')"), sqlite_where=sa.text("status IN ('running', 'paused')"))
        batch_op.drop_index(batch_op.f('ix_technical_test_sessions_workstation_id'))
        batch_op.drop_index(batch_op.f('ix_technical_test_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_technical_test_sessions_candidate_id'))

    op.drop_table('technical_test_sessions')
    with op.batch_alter_table('kobo_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kobo_submissions_match_status'))
        batch_op.drop_index(batch_op.f('ix_kobo_submissions_candidate_id'))

    op.drop_table('kobo_submissions')
    with op.batch_alter_table('workstations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workstations_room_id'))

    op.drop_table('workstations')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_technical_completed'))
        batch_op.drop_index(batch_op.f('ix_candidates_scheduled_date'))
        batch_op.drop_index(batch_op.f('ix_candidates_physical_file_status'))
        batch_op.drop_index(batch_op.f('ix_candidates_phone'))
        batch_op.drop_index(batch_op.f('ix_candidates_motivation_completed'))
        batch_op.drop_index(batch_op.f('ix_candidates_group_name'))
        batch_op.drop_index(batch_op.f('ix_candidates_full_name'))
        batch_op.drop_index(batch_op.f('ix_candidates_email'))
        batch_op.drop_index(batch_op.f('ix_candidates_cni'))
        batch_op.drop_index(batch_op.f('ix_candidates_candidate_number'))

    op.drop_table('candidates')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('rooms')
    # ### end Alembic commands ###
